name: "Release Cycle: Start"

on:
  workflow_dispatch:
    inputs:
      final_version:
        description: 'The final version you want to release.'
        required: true

jobs:
  # https://til.simonwillison.net/github-actions/dump-context
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  build-first-release-candidate:
    name: "Build first release candidate"
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      # Enable under repository settings
      pull-requests: write
    env:
      FINAL_VERSION: ${{ github.event.inputs.final_version }}
      RC_VERSION: ${{ github.event.inputs.final_version }}-rc.1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      # - name: Set final version
      #   run: echo "FINAL_VERSION=$(cat VERSION | sed 's/-dev//g')" >> $GITHUB_ENV
      # - name: Set RC version
      #   run: echo "RC_VERSION=$FINAL_VERSION-rc.1" >> $GITHUB_ENV
      - name: Create release branch
        run: git checkout -b release/${{ env.FINAL_VERSION }}
      - name: Update VERSION file
        run: echo ${{ env.RC_VERSION }} > VERSION
      - name: Commit VERSION
        id: make-commit
        run: |
          git add VERSION
          git commit --message "[RELEASE] ${{ env.RC_VERSION }}"
      - name: Push new branch
        run: git push origin release/${{ env.FINAL_VERSION }}
      - name: Create a tag
        run: |
          git tag v${{ env.RC_VERSION }}
          git push origin v${{ env.RC_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RC_VERSION }}
          tag_name: v${{ env.RC_VERSION }}
          generate_release_notes: true
          prerelease: true
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ env.FINAL_VERSION }}
          base: main
          title: "[RELEASE] ${{ env.FINAL_VERSION }}"
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated VERSION in this commit: ${{ steps.make-commit.outputs.commit }}.
