name: "Release Cycle: Next RC"

on:
  workflow_dispatch:
    inputs:
      final_version:
        description: 'The final version to release.'
        required: true
      rc_number:
        description: 'The next RC number in this release.'
        required: true

jobs:
  build-next-rc:
    name: "Build the next release candidate"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FINAL_VERSION: ${{ github.event.inputs.final_version }}
      RC_VERSION: ${{ github.event.inputs.final_version }}-rc.${{ github.event.inputs.rc_number }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/${{ env.FINAL_VERSION }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Update VERSION file
        run: echo ${{ env.RC_VERSION }} > VERSION
      - name: Commit VERSION
        run: |
          git add VERSION
          git commit --message "[RELEASE] ${{ env.RC_VERSION }}"
          git push origin release/${{ env.FINAL_VERSION }}
      - name: Create a tag
        run: |
          git tag v${{ env.RC_VERSION }}
          git push origin v${{ env.RC_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RC_VERSION }}
          tag_name: v${{ env.RC_VERSION }}
          generate_release_notes: true
          prerelease: true
